// src/constants/permissions.js

const PERMISSIONS = {
  // Business
  CREATE_BUSINESS: 'CREATE_BUSINESS',
  READ_BUSINESS: 'READ_BUSINESS',
  UPDATE_BUSINESS: 'UPDATE_BUSINESS',
  DELETE_BUSINESS: 'DELETE_BUSINESS',
  MANAGE_BUSINESS: 'MANAGE_BUSINESS',

  // Owner
  CREATE_OWNER: 'CREATE_OWNER',
  READ_OWNER: 'READ_OWNER',
  UPDATE_OWNER: 'UPDATE_OWNER',
  DELETE_OWNER: 'DELETE_OWNER',
  MANAGE_OWNER: 'MANAGE_OWNER',

  // Product Segment
  CREATE_PRODUCT_SEGMENT: 'CREATE_PRODUCT_SEGMENT',
  READ_PRODUCT_SEGMENT: 'READ_PRODUCT_SEGMENT',
  UPDATE_PRODUCT_SEGMENT: 'UPDATE_PRODUCT_SEGMENT',
  DELETE_PRODUCT_SEGMENT: 'DELETE_PRODUCT_SEGMENT',
  MANAGE_PRODUCT_SEGMENT: 'MANAGE_PRODUCT_SEGMENT',

  // Product Category
  CREATE_PRODUCT_CATEGORY: 'CREATE_PRODUCT_CATEGORY',
  READ_PRODUCT_CATEGORY: 'READ_PRODUCT_CATEGORY',
  UPDATE_PRODUCT_CATEGORY: 'UPDATE_PRODUCT_CATEGORY',
  DELETE_PRODUCT_CATEGORY: 'DELETE_PRODUCT_CATEGORY',
  MANAGE_PRODUCT_CATEGORY: 'MANAGE_PRODUCT_CATEGORY',

  // Product Model
  CREATE_PRODUCT_MODEL: 'CREATE_PRODUCT_MODEL',
  READ_PRODUCT_MODEL: 'READ_PRODUCT_MODEL',
  UPDATE_PRODUCT_MODEL: 'UPDATE_PRODUCT_MODEL',
  DELETE_PRODUCT_MODEL: 'DELETE_PRODUCT_MODEL',
  MANAGE_PRODUCT_MODEL: 'MANAGE_PRODUCT_MODEL',

  // Product Images
  CREATE_PRODUCT_IMAGE: 'CREATE_PRODUCT_IMAGE',
  READ_PRODUCT_IMAGE: 'READ_PRODUCT_IMAGE',
  UPDATE_PRODUCT_IMAGE: 'UPDATE_PRODUCT_IMAGE',
  DELETE_PRODUCT_IMAGE: 'DELETE_PRODUCT_IMAGE',
  MANAGE_PRODUCT_IMAGE: 'MANAGE_PRODUCT_IMAGE',

  // User Management
  CREATE_USER: 'CREATE_USER',
  READ_USER: 'READ_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  MANAGE_USER: 'MANAGE_USER',

  // Session & OTP
  MANAGE_SESSION: 'MANAGE_SESSION',
  MANAGE_OTP: 'MANAGE_OTP',
};

module.exports = PERMISSIONS;